/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        charcoal: '#0D0D0D',
        gold: '#D4A452',
        deepgold: '#B87A32',
        ivory: '#F6F4EE',
        cream: '#FFFDF7',
        sand: '#E7DCC6',
        sage: '#4E6B4F',
        "on-tertiary": "#ffffff",
        "outline": "#747872",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2de",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b8ccb7",
        "secondary-fixed": "#ffddb7",
        "error": "#ba1a1a",
        "tertiary": "#242422",
        "surface-container-low": "#f6f3ef",
        "on-primary-fixed": "#0f1f12",
        "on-surface": "#1c1c19",
        "on-secondary-container": "#784d09",
        "primary-container": "#2d3e2f",
        "on-surface-variant": "#434842",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e5e2dd",
        "on-tertiary-fixed-variant": "#474743",
        "surface-container-highest": "#e5e2de",
        "secondary": "#815513",
        "outline-variant": "#c3c8c0",
        "background": "#fcf9f5",
        "on-primary-container": "#96a995",
        "on-primary": "#ffffff",
        "tertiary-container": "#3a3a37",
        "secondary-container": "#fdc175",
        "on-tertiary-container": "#a5a49f",
        "on-tertiary-fixed": "#1c1c19",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b8ccb7",
        "secondary-fixed-dim": "#f7bc71",
        "on-secondary-fixed": "#2a1700",
        "surface-container": "#f0ede9",
        "primary-fixed": "#d4e8d3",
        "inverse-on-surface": "#f3f0ec",
        "surface": "#fcf9f5",
        "on-primary-fixed-variant": "#3a4b3b",
        "surface-tint": "#516352",
        "surface-bright": "#fcf9f5",
        "primary": "#18281a",
        "inverse-surface": "#31302e",
        "on-background": "#1c1c19",
        "on-error-container": "#93000a",
        "surface-container-high": "#ebe8e4",
        "on-secondary-fixed-variant": "#653e00",
        "surface-dim": "#dcdad6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1280px",
        "stack-md": "16px",
        "section-gap": "120px",
        "margin-desktop": "64px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "gutter": "24px"
      },
      fontFamily: {
        serif: ['Playfair Display', 'Georgia', 'serif'],
        sans: ['Inter', 'Arial', 'sans-serif'],
        "label-md": ["Manrope"],
        "headline-md": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "body-lg": ["Manrope"],
        "label-sm": ["Manrope"],
        "display-lg-mobile": ["Playfair Display"],
        "body-md": ["Manrope"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["36px", {"lineHeight": "1.3", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "1.4", "fontWeight": "400"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
